In [2]:
import numpy as np
import numpy

def calc_expectations(h, w, X, Q):
    sums = np.cumsum(np.cumsum(Q, axis=0), axis=1)
    
    left = np.roll(sums, w, axis=1)
    left[:, 0:w] = 0
    
    up = np.roll(sums, h, axis=0)
    up[0:h, :] = 0
    
    leftUp = np.roll(np.roll(sums, w, axis=1), h, axis=0)
    leftUp[:, 0:w] = 0
    leftUp[0:h, :] = 0
    
    prob = sums - left - up + leftUp
    return prob * X
    
h, w = 2, 2

X = np.asarray([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4],
], dtype=int)

Q = np.asarray([
    [0.20, 0.  , 0.3 , 0.1 ],
    [0.10, 0.  , 0.2 , 0.  ],
    [0.05, 0.  , 0.  , 0.  ],
    [0.  , 0.  , 0.  , 0.05],
], dtype=float)

calc_expectations(h,w,X,Q)
# X = np.arange(9).reshape(3,-1)
# sums = np.cumsum(np.cumsum(X, axis=0), axis=1)
# sums

array([[0.2 , 0.2 , 0.3 , 0.4 ],
       [0.6 , 0.6 , 1.  , 1.2 ],
       [0.45, 0.45, 0.6 , 0.6 ],
       [0.2 , 0.2 , 0.  , 0.2 ]])

In [102]:
left = np.roll(sums, w, axis=1)
left[:, 0:w] = 0
left

array([[0, 0, 0],
       [0, 0, 3],
       [0, 0, 9]])

In [103]:
up = np.roll(sums, h, axis=0)
up[0:h, :] = 0
up

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 3]])

In [106]:
diag = np.roll(np.roll(sums, w, axis=1), h, axis=0)
diag[:, 0:w] = 0
diag[0:h, :] = 0
diag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
sums - left - up + diag

array([[ 0,  1,  3],
       [ 3,  8, 12],
       [ 9, 20, 24]])

In [39]:
import random
x = [random.randint(1, 10000000) for _ in range(1000000)]



In [40]:
%%timeit

y = np.array(x)
def encode_rle(X):
    n = len(X)
    unequalsFlags = np.array(X[1:] != X[:-1]) 
    unequalsIndecies = np.append(np.where(unequalsFlags), n - 1)
    counts = np.diff(np.append(-1, unequalsIndecies))
    return (X[unequalsIndecies], counts)

encode_rle(y)

72.7 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%%timeit

def encode_rle_python(x):
    prevElement = None
    result = ([], [])
    currentCount = 0
    for element in x:
        if prevElement is None:
            currentCount = 1
        elif element == prevElement:
            currentCount += 1
        else:
            result[0].append(prevElement)
            result[1].append(currentCount)
            currentCount = 1
        prevElement = element
    result[0].append(prevElement)
    result[1].append(currentCount)
    return result


encode_rle_python(x)

218 ms ± 11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
import numpy as np

x = np.array([[16, 10,  3,  8, 14,  5,  6, 18,  4, 17, 12,  2, 19,  1,  0],
       [ 6,  4, 19, 15, 13, 11, 14,  0,  7, 18,  9, 12,  8, 17,  1],
       [ 9, 12,  1,  2, 11, 17, 19,  8, 13, 15, 16, 10,  0, 18,  7]])


def get_best_indices(ranks, top, axis=1):
    indexes = np.argpartition(-ranks, top - 1, axis=axis).take(indices=range(0, top), axis=axis)
    values = np.take_along_axis(-ranks, indexes, axis=axis)
    cuttedSortedIndexes = np.argsort(values, axis=axis)
    return np.take_along_axis(indexes, cuttedSortedIndexes, axis=axis)

# np.argsort(-x, axis = 1)
# indexes = np.argpartition(-x, 5, axis = 1)[:, :5]
# np.take_along_axis(indexes, np.argsort(np.take_along_axis(-x, indexes, axis = 1), axis = 1), axis = 1)
get_best_indices(x, 5, 1)

array([[12,  7,  9,  0,  4],
       [ 2,  9, 13,  3,  6],
       [ 6, 13,  5, 10,  9]])

In [7]:
1e1 1e2   1e3     1e4      1e5      1e6        1e7
 20  20    26      73      540      8500       150000
  2  20   200    1900    20000      223000     2000000

10

In [4]:
def foo(x):
    if x + 1 is 1 + x:
        return False
    if x + 2 is not 2 + x:
        return False
    return True

foo(-7)


True

In [6]:
def hello(name = "Stranger"):
    print(f'Hello {name}')

In [8]:
hello()

Hello Stranger


In [37]:
def maximum(x):
    def maximum1(x, element):
        if len(x) == 0:
            return element
        else:
            return maximum1(x[1:], element) if x[0] < element else maximum1(x[1:], x[0])
    return maximum1(x, x[0])

print(maximum([3,4,5,1,2]))


5


In [ ]:
memo = {}
def fibbonaci(n):
     if n <= 2: 
        return 1
     else:
        left = memo[n - 1] if n - 1 in memo else fibbonaci(n - 1)
        right = memo[n - 2] if n - 2 in memo else fibbonaci(n - 2)
        memo[n] = left + right
        return memo[n]
    
print(fibbonaci(2400))