In [109]:
import numpy as np
import numpy

def calc_expectations(h, w, X, Q):
    sums = np.cumsum(np.cumsum(Q, axis=0), axis=1)
    
    left = np.roll(sums, w, axis=1)
    left[:, 0:w] = 0
    
    up = np.roll(sums, h, axis=0)
    up[0:h, :] = 0
    
    leftUp = np.roll(np.roll(sums, w, axis=1), h, axis=0)
    leftUp[:, 0:w] = 0
    leftUp[0:h, :] = 0
    
    prob = sums - left - up + leftUp
    return prob * X
    
h, w = 2, 2

X = np.asarray([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4],
], dtype=int)

Q = np.asarray([
    [0.20, 0.  , 0.3 , 0.1 ],
    [0.10, 0.  , 0.2 , 0.  ],
    [0.05, 0.  , 0.  , 0.  ],
    [0.  , 0.  , 0.  , 0.05],
], dtype=float)

calc_expectations(h,w,X,Q)
# X = np.arange(9).reshape(3,-1)
# sums = np.cumsum(np.cumsum(X, axis=0), axis=1)
# sums

array([[0.2 , 0.2 , 0.3 , 0.4 ],
       [0.6 , 0.6 , 1.  , 1.2 ],
       [0.45, 0.45, 0.6 , 0.6 ],
       [0.2 , 0.2 , 0.  , 0.2 ]])

In [102]:
left = np.roll(sums, w, axis=1)
left[:, 0:w] = 0
left

array([[0, 0, 0],
       [0, 0, 3],
       [0, 0, 9]])

In [103]:
up = np.roll(sums, h, axis=0)
up[0:h, :] = 0
up

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 3]])

In [106]:
diag = np.roll(np.roll(sums, w, axis=1), h, axis=0)
diag[:, 0:w] = 0
diag[0:h, :] = 0
diag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
sums - left - up + diag

array([[ 0,  1,  3],
       [ 3,  8, 12],
       [ 9, 20, 24]])

In [121]:
import random
x = [random.randint(1,10) for _ in range(10000)]

In [122]:
%%timeit
y = np.array(x)
def encode_rle(X):
    n = len(X)
    unequalsFlags = np.array(X[1:] != X[:-1]) 
    unequalsIndecies = np.append(np.where(unequalsFlags), n - 1)
    counts = np.diff(np.append(-1, unequalsIndecies))
    return (X[unequalsIndecies], counts)

encode_rle(y)

1.83 ms ± 216 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [123]:
%%timeit

def encode_rle_python(x):
    prevElement = None
    result = ([], [])
    currentCount = 0
    for element in x:
        if prevElement is None:
            currentCount = 1
        elif element == prevElement:
            currentCount += 1
        else:
            result[0].append(prevElement)
            result[1].append(currentCount)
            currentCount = 1
        prevElement = element
    result[0].append(prevElement)
    result[1].append(currentCount)
    return result


encode_rle_python(x)

6.29 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
import numpy as np

x = np.array([[16, 10,  3,  8, 14,  5,  6, 18,  4, 17, 12,  2, 19,  1,  0],
       [ 6,  4, 19, 15, 13, 11, 14,  0,  7, 18,  9, 12,  8, 17,  1],
       [ 9, 12,  1,  2, 11, 17, 19,  8, 13, 15, 16, 10,  0, 18,  7]])


def get_best_indices(ranks, top, axis=1):
    indexes = np.argpartition(-ranks, top - 1, axis=axis).take(indices=range(0, top), axis=axis)
    values = np.take_along_axis(-ranks, indexes, axis=axis)
    cuttedSortedIndexes = np.argsort(values, axis=axis)
    return np.take_along_axis(indexes, cuttedSortedIndexes, axis=axis)

# np.argsort(-x, axis = 1)
# indexes = np.argpartition(-x, 5, axis = 1)[:, :5]
# np.take_along_axis(indexes, np.argsort(np.take_along_axis(-x, indexes, axis = 1), axis = 1), axis = 1)
get_best_indices(x, 5, 1)

array([[12,  7,  9,  0,  4],
       [ 2,  9, 13,  3,  6],
       [ 6, 13,  5, 10,  9]])

In [245]:
class Test:
    def __init__(self, x):
        self.x = x
    
    def __add__(self, z):
        return z != 3
    
    def __radd__(self, z):
        return z == 2  # adding two objects 
   
def foo(x):
    if x + 1 is 1 + x:
        return False
    if x + 2 is not 2 + x:
        return False
    return True

foo(Test(0))


True